# Generated by Django 2.0.2 on 2019-03-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20190301_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footerDescription', models.TextField(blank=True, max_length=500, null=True)),
                ('twitterLink', models.URLField(blank=True, null=True)),
                ('facebookLink', models.URLField(blank=True, null=True)),
                ('instagramLink', models.URLField(blank=True, null=True)),
                ('linkedinLink', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
