# Generated by Django 2.0.2 on 2019-03-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_portfoliocategories_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': '2. About Us'},
        ),
        migrations.AlterModelOptions(
            name='belowaboutus',
            options={'verbose_name_plural': '3. Below About Us '},
        ),
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name_plural': '4. Call to action '},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '12. Contact '},
        ),
        migrations.AlterModelOptions(
            name='contactdescription',
            options={'verbose_name_plural': '11. Contact Description '},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': '13. Footer '},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategories',
            options={'verbose_name_plural': '7. Portfolio Categories '},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '8. Projects '},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': '6. Skill '},
        ),
        migrations.AlterModelOptions(
            name='skillsdescription',
            options={'verbose_name_plural': '5. Skills Description '},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '1. Sliders '},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': '10. Team '},
        ),
        migrations.AlterModelOptions(
            name='teamdescription',
            options={'verbose_name_plural': '9. Team Description '},
        ),
    ]
