# Generated by Django 2.0.2 on 2019-03-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20190305_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': '2. AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='belowaboutus',
            options={'verbose_name_plural': '3. BelowAboutUs'},
        ),
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name_plural': '4. Calltoaction'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '12. Contact'},
        ),
        migrations.AlterModelOptions(
            name='contactdescription',
            options={'verbose_name_plural': '11. ContactDescription'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': '13. Footer'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategories',
            options={'verbose_name_plural': '7. PortfolioCategories'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '8. Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': '6. Skill'},
        ),
        migrations.AlterModelOptions(
            name='skillsdescription',
            options={'verbose_name_plural': '5. SkillsDescription'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '1. Sliders'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': '10. Team'},
        ),
        migrations.AlterModelOptions(
            name='teamdescription',
            options={'verbose_name_plural': '9. TeamDescription'},
        ),
    ]
