# Generated by Django 2.0.2 on 2019-03-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20190305_0624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': '1.2 AboutUs'},
        ),
        migrations.AlterModelOptions(
            name='belowaboutus',
            options={'verbose_name_plural': '1.3 BelowAboutUs'},
        ),
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name_plural': '1.4 Calltoaction'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': '3.2 Contact'},
        ),
        migrations.AlterModelOptions(
            name='contactdescription',
            options={'verbose_name_plural': '3.1 ContactDescription'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': '3.3 Footer'},
        ),
        migrations.AlterModelOptions(
            name='portfoliocategories',
            options={'verbose_name_plural': '2.2 PortfolioCategories'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '2.3 Projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name_plural': '2.1 Skill'},
        ),
        migrations.AlterModelOptions(
            name='skillsdescription',
            options={'verbose_name_plural': '1.5 SkillsDescription'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '1.1 Sliders'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': '2.5 Team'},
        ),
        migrations.AlterModelOptions(
            name='teamdescription',
            options={'verbose_name_plural': '2.4 TeamDescription'},
        ),
    ]
