# Generated by Django 2.0.2 on 2019-03-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_auto_20190305_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sliderImage',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
