# Generated by Django 2.0.2 on 2019-03-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20190305_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='belowaboutus',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
