# Generated by Django 2.0.2 on 2019-03-05 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_belowaboutus_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='belowaboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
