# Generated by Django 2.0.2 on 2019-03-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_belowaboutus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='startSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('sliderImage', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': '1.1 Sliders',
            },
        ),
    ]
