# Generated by Django 2.0.2 on 2019-03-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20190307_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skillColor',
            field=models.CharField(blank=True, help_text='Insert these colors. success = Green, info =  blue, warning = yellow, danger = red', max_length=150, null=True),
        ),
    ]
