# Generated by Django 2.0.2 on 2019-03-07 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_skill_skillcolor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skillPercentage'], 'verbose_name_plural': '2.2 Skill'},
        ),
    ]
