# Generated by Django 2.0.2 on 2019-03-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20190307_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['-skillPercentage'], 'verbose_name_plural': '2.2 Skill'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='title',
            new_name='position',
        ),
    ]
