# Generated by Django 2.0.2 on 2019-03-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20190307_0736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='header',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='icon',
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
